Repository myfitroutine/myfitroutine, pull requests merged in 2023-12, with the labels that each got.

#8 [Feat] gragh page graph 기능 구현
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/java/com/bestteam/myfitroutine/Dialog/FilteredDateDialog.kt
  app/src/main/java/com/bestteam/myfitroutine/Dialog/GetGoalWeightFragment.kt
  app/src/main/java/com/bestteam/myfitroutine/View/GraphFragment.kt
  app/src/main/java/com/bestteam/myfitroutine/View/MainFragment.kt
  app/src/main/java/com/bestteam/myfitroutine/ViewModel/GraghViewModel.kt
  app/src/main/java/com/bestteam/myfitroutine/ViewModel/MainViewModel.kt
  app/src/main/res/layout/fragment_get_goal_weight.xml
  app/src/main/res/layout/fragment_gragh.xml
  app/src/main/res/layout/fragment_main.xml
  build.gradle.kts
  settings.gradle.kts
Labels: feature

#14 [Feat] Login page / SignUp Page 기능 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/bestteam/myfitroutine/LogIn/FirstMainActivity.kt
  app/src/main/java/com/bestteam/myfitroutine/LogIn/LogInActivity.kt
  app/src/main/java/com/bestteam/myfitroutine/SignUp/SignUpActivity.kt
  app/src/main/java/com/bestteam/myfitroutine/SignUp/UserData.kt
  app/src/main/java/com/bestteam/myfitroutine/View/MainFragment.kt
  app/src/main/res/drawable/first_pg_button.xml
  app/src/main/res/drawable/ic_firstpage.png
  app/src/main/res/layout/activity_first_main.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_signup.xml
Labels: feature

#16 [Design] 식단페이지
  app/src/main/java/com/bestteam/myfitroutine/View/MealFragment.kt
  app/src/main/res/drawable/btn_delete.png
  app/src/main/res/drawable/btn_plus.png
  app/src/main/res/drawable/btn_search.png
  app/src/main/res/drawable/meal_dialog_shape.xml
  app/src/main/res/drawable/meal_image.png
  app/src/main/res/drawable/meal_radius1.xml
  app/src/main/res/drawable/meal_radius2.xml
  app/src/main/res/drawable/meal_radius3.xml
  app/src/main/res/layout/fragment_meal.xml
  app/src/main/res/layout/meal_dialog.xml
  app/src/main/res/layout/meal_dialog_item.xml
  app/src/main/res/layout/meal_record_item.xml
  app/src/main/res/layout/meal_today_item.xml
Labels: design

#18 [Design] 일정 페이지 UI 작업
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/bestteam/myfitroutine/View/DiaryFragment.kt
  app/src/main/res/drawable/diary_image.png
  app/src/main/res/drawable/diary_target_btn.xml
  app/src/main/res/layout/dialog_edit_target_diary.xml
  app/src/main/res/layout/dialog_target_diary.xml
  app/src/main/res/layout/fragment_diary.xml
  app/src/main/res/layout/recyclerview_date_diary.xml
  app/src/main/res/layout/recyclerview_target_diary.xml
  app/src/main/res/layout/recyclerview_todaytarget_diary.xml
Labels: design

#22 [Design] 일정 페이지 UI 작업(내일 목표 정하기 부분 수정)
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_target_diary.xml
Labels: design

#24 [Feat] getGoalWeight 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/bestteam/myfitroutine/Dialog/FilterDateDialog.kt
  app/src/main/java/com/bestteam/myfitroutine/Dialog/GetGoalWeightDialog.kt
  app/src/main/java/com/bestteam/myfitroutine/Model/WeightData.kt
  app/src/main/java/com/bestteam/myfitroutine/Repository/MainRepository.kt
  app/src/main/java/com/bestteam/myfitroutine/SignUp/SignUpActivity.kt
  app/src/main/java/com/bestteam/myfitroutine/View/GraphFragment.kt
  app/src/main/java/com/bestteam/myfitroutine/View/MainFragment.kt
  app/src/main/java/com/bestteam/myfitroutine/ViewModel/GraghViewModel.kt
  app/src/main/java/com/bestteam/myfitroutine/ViewModel/MainViewModel.kt
  app/src/main/res/layout/fragment_get_goal_weight.xml
  app/src/main/res/layout/fragment_gragh.xml
Labels: feature

#30 [Design] main_page, graph_page dialogs UI
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-12-07__3_17__Changes_.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-12-07_오후_3_17_[Changes]/shelved.patch
  app/build.gradle.kts
  app/src/main/java/com/bestteam/myfitroutine/Dialog/GetGoalWeightDialog.kt
  app/src/main/java/com/bestteam/myfitroutine/Dialog/TodayWeightDialog.kt
  app/src/main/java/com/bestteam/myfitroutine/LogIn/LogInActivity.kt
  app/src/main/java/com/bestteam/myfitroutine/Util/CustomToast.kt
  app/src/main/java/com/bestteam/myfitroutine/View/MainFragment.kt
  app/src/main/java/com/bestteam/myfitroutine/ViewModel/MainViewModel.kt
  app/src/main/res/drawable/avata_background.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_filter_date_dialog.xml
  app/src/main/res/layout/fragment_get_goal_weight.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_today_weight_dialog.xml
  app/src/main/res/layout/toast_layout.xml
Labels: design

#32 [Design] graph_page UI
  app/src/main/java/com/bestteam/myfitroutine/Dialog/FilterDateDialog.kt
  app/src/main/java/com/bestteam/myfitroutine/Repository/MainRepository.kt
  app/src/main/java/com/bestteam/myfitroutine/SignUp/SignUpActivity.kt
  app/src/main/java/com/bestteam/myfitroutine/View/GraphFragment.kt
  app/src/main/java/com/bestteam/myfitroutine/View/MainFragment.kt
  app/src/main/res/drawable/chart_box.xml
  app/src/main/res/drawable/underline_style.xml
  app/src/main/res/layout/custom_marker_view.xml
  app/src/main/res/layout/fragment_filter_date_dialog.xml
  app/src/main/res/layout/fragment_gragh.xml
  app/src/main/res/values/strings.xml
Labels: design

#34 [Fix] graph_page
  app/src/main/java/com/bestteam/myfitroutine/Dialog/FilterDateDialog.kt
  app/src/main/java/com/bestteam/myfitroutine/View/GraphFragment.kt
  app/src/main/res/layout/custom_marker_view.xml
Labels: bug

#36 [Feat] login_page 자동로그인 기능 구현
  app/src/main/java/com/bestteam/myfitroutine/LogIn/FirstMainActivity.kt
  app/src/main/java/com/bestteam/myfitroutine/LogIn/LogInActivity.kt
Labels: feature

#37 [Feat] 식단페이지 retrofit 연결
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/bestteam/myfitroutine/Adapter/MealDialogSearchAdapter.kt
  app/src/main/java/com/bestteam/myfitroutine/Contain.kt
  app/src/main/java/com/bestteam/myfitroutine/Dialog/MealPlusDialog.kt
  app/src/main/java/com/bestteam/myfitroutine/Model/Meal_AIP_Data.kt
  app/src/main/java/com/bestteam/myfitroutine/Model/Meal_Adapter_Data.kt
  app/src/main/java/com/bestteam/myfitroutine/Repository/MealRepository.kt
  app/src/main/java/com/bestteam/myfitroutine/ViewModel/MealViewModel.kt
  app/src/main/java/com/bestteam/myfitroutine/retrofit/NetworkClient.kt
  app/src/main/java/com/bestteam/myfitroutine/retrofit/NetworkInterface.kt
  app/src/main/res/drawable/fragment_shape.xml
  app/src/main/res/layout/fragment_meal.xml
  app/src/main/res/layout/meal_dialog.xml
  app/src/main/res/layout/meal_dialog_search_item.xml
Labels: feature

#44 [Design] graph_page UI 수정
  app/src/main/java/com/bestteam/myfitroutine/View/MainFragment.kt
  app/src/main/res/drawable/btn_back.xml
  app/src/main/res/drawable/icn_scale.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_gragh.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/values/strings.xml
Labels: design

#46 [Feat] 식단페이지 다이얼로그 검색결과 클릭Feature/meal page
  app/src/main/java/com/bestteam/myfitroutine/Adapter/MealDialogResultAdapter.kt
  app/src/main/java/com/bestteam/myfitroutine/Adapter/MealDialogSearchAdapter.kt
  app/src/main/java/com/bestteam/myfitroutine/Dialog/MealPlusDialog.kt
  app/src/main/java/com/bestteam/myfitroutine/Model/Meal_AIP_Data.kt
  app/src/main/java/com/bestteam/myfitroutine/Model/Meal_Adapter_Data.kt
  app/src/main/java/com/bestteam/myfitroutine/ViewModel/MealPlusViewModel.kt
  app/src/main/res/color/chip_check_background.xml
  app/src/main/res/color/chip_check_text.xml
  app/src/main/res/layout/meal_dialog.xml
  app/src/main/res/layout/meal_dialog_result_item.xml
  app/src/main/res/layout/meal_dialog_search_item.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: feature

#51 [Feat] graph_page 그래프 기간설정 수정
  app/src/main/java/com/bestteam/myfitroutine/Dialog/FilterDateDialog.kt
  app/src/main/java/com/bestteam/myfitroutine/View/GraphFragment.kt
  app/src/main/java/com/bestteam/myfitroutine/ViewModel/GraghViewModel.kt
  app/src/main/res/layout/fragment_gragh.xml
  app/src/main/res/layout/fragment_today_weight_dialog.xml
Labels: feature

#53 [Fix] 메인페이지,그래프페이지 예외처리 수정
  app/src/main/java/com/bestteam/myfitroutine/Dialog/FilterDateDialog.kt
  app/src/main/java/com/bestteam/myfitroutine/Dialog/GetGoalWeightDialog.kt
  app/src/main/java/com/bestteam/myfitroutine/Dialog/TodayWeightDialog.kt
  app/src/main/java/com/bestteam/myfitroutine/View/GraphFragment.kt
  app/src/main/res/layout/fragment_filter_date_dialog.xml
  app/src/main/res/layout/fragment_get_goal_weight.xml
  app/src/main/res/layout/fragment_gragh.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_today_weight_dialog.xml
Labels: bug

#54 [Feat] 일정 다이어로그 버튼 수정
  app/src/main/res/layout/dialog_edit_target_diary.xml
  app/src/main/res/layout/dialog_target_diary.xml
Labels: feature

#55 [Feat] : 식단페이지 다이얼로그 기능 마무리하기
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/bestteam/myfitroutine/Adapter/MealDailyAdapter.kt
  app/src/main/java/com/bestteam/myfitroutine/Dialog/MealPlusDialog.kt
  app/src/main/java/com/bestteam/myfitroutine/Model/Meal_Adapter_Data.kt
  app/src/main/java/com/bestteam/myfitroutine/Model/TotalNumData.kt
  app/src/main/java/com/bestteam/myfitroutine/View/MealFragment.kt
  app/src/main/res/color/chip_check_background.xml
  app/src/main/res/layout/fragment_meal.xml
  app/src/main/res/layout/meal_dialog.xml
  app/src/main/res/layout/meal_today_item.xml
Labels: feature

#58 [Design] 로그인 페이지, 회원가입 페이지 UI 수정
  app/src/main/java/com/bestteam/myfitroutine/LogIn/FirstMainActivity.kt
  app/src/main/res/drawable/bg_first.png
  app/src/main/res/drawable/icn_shoe.png
  app/src/main/res/drawable/login_signup_blank.xml
  app/src/main/res/drawable/login_txt.png
  app/src/main/res/layout/activity_first_main.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/values/strings.xml
Labels: design

#61 [Feat] 메인페이지 Avata 변경 추가
  app/src/main/java/com/bestteam/myfitroutine/Dialog/AvataDialog.kt
  app/src/main/java/com/bestteam/myfitroutine/View/MainFragment.kt
  app/src/main/java/com/bestteam/myfitroutine/ViewModel/MainViewModel.kt
  app/src/main/res/drawable/avata_2.png
  app/src/main/res/drawable/avata_3.png
  app/src/main/res/drawable/avata_4.png
  app/src/main/res/drawable/icn_edit.png
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/fragment_avata_dialog.xml
  app/src/main/res/layout/fragment_main.xml
Labels: feature

#63 [Feat] 오늘의 추천동영상 기능 추가, Hilt를 사용하여 종속성주입 마이그레이션
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/bestteam/myfitroutine/Adapter/YoutubeAdapter.kt
  app/src/main/java/com/bestteam/myfitroutine/Contain.kt
  app/src/main/java/com/bestteam/myfitroutine/Dialog/MealPlusDialog.kt
  app/src/main/java/com/bestteam/myfitroutine/MainActivity.kt
  app/src/main/java/com/bestteam/myfitroutine/Model/VideoItem.kt
  app/src/main/java/com/bestteam/myfitroutine/Model/YoutubeApi.kt
  app/src/main/java/com/bestteam/myfitroutine/MyFitRoutineApplication.kt
  app/src/main/java/com/bestteam/myfitroutine/Repository/MainRepository.kt
  app/src/main/java/com/bestteam/myfitroutine/Repository/YoutubeRepository.kt
  app/src/main/java/com/bestteam/myfitroutine/View/GraphFragment.kt
  app/src/main/java/com/bestteam/myfitroutine/View/MainFragment.kt
  app/src/main/java/com/bestteam/myfitroutine/View/VideoDetailActivity.kt
  app/src/main/java/com/bestteam/myfitroutine/ViewModel/MainViewModel.kt
  app/src/main/java/com/bestteam/myfitroutine/ViewModel/MealPlusViewModel.kt
  app/src/main/java/com/bestteam/myfitroutine/retrofit/MainRepositoryModule.kt
  app/src/main/java/com/bestteam/myfitroutine/retrofit/Youtube_client.kt
  app/src/main/java/com/bestteam/myfitroutine/retrofit/Youtube_interface.kt
  app/src/main/res/drawable/play_circle.png
  app/src/main/res/layout/activity_video_detail.xml
  app/src/main/res/layout/fragment_gragh.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_meal.xml
  app/src/main/res/layout/video_item.xml
  app/src/test/java/com/bestteam/myfitroutine/ExampleUnitTest.kt
  build.gradle.kts
Labels: feature

#65 [Feat] Video 페이지 동영상기능 구현
  app/src/main/java/com/bestteam/myfitroutine/Adapter/YoutubeAdapter.kt
  app/src/main/java/com/bestteam/myfitroutine/Model/VideoItem.kt
  app/src/main/java/com/bestteam/myfitroutine/View/VideoDetailActivity.kt
  app/src/main/java/com/bestteam/myfitroutine/ViewModel/MainViewModel.kt
  app/src/main/res/layout/activity_video_detail.xml
Labels: feature
